### ISSUE TITLE
Installation error with numpy and test failure

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-cryocare#17]
When installing, at the last step I get the following error
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-gpu 2.3.3 requires numpy<1.19.0,>=1.16.0, but you have numpy 1.23.5 which is incompatible.
Successfully installed contourpy-1.0.6 cryoCARE-0.1.1 csbdeep-0.6.3 cycler-0.11.0 fonttools-4.38.0 install-1.3.5 keras-2.3.1 keras-applications-1.0.8 kiwisolver-1.4.4 matplotlib-3.6.2 numpy-1.23.5 packaging-21.3 pillow-9.3.0 psutil-5.9.4 pyparsing-3.0.9 python-dateutil-2.8.2 pyyaml-6.0 scipy-1.9.3 tifffile-2022.10.10 tqdm-4.64.1
  Skipping command: Link 'cryoCARE-0.1.1 -> cryoCARE-0.1.1'
  All targets exist.
Done (2 m 14 s)
```
When testing I get the following. 

```

(base) harastamadm@PC4-0002-D:/shared/scipion3/plugins/scipion-em-cryocare$ scipion3 tests --grep cryocare 
Scipion v3.0.12 - Eugenius
Running tests....
 scipion3 tests cryocare.tests.test_cryoCARE_workflow
   scipion3 tests cryocare.tests.test_cryoCARE_workflow.TestCryoCARE
(base) harastamadm@PC4-0002-D:/shared/scipion3/plugins/scipion-em-cryocare$ scipion3 tests cryocare.tests.test_cryoCARE_workflow
Scipion v3.0.12 - Eugenius
Running tests....
Creating project at /media/SharedDisk/ScipionProjects/projects/TestCryoCARE/project.sqlite
>>>> python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_sync_data.py --download cryocare 
Selected datasets: cryocare
Dataset cryocare not in local machine. Downloading...
Fetching files of dataset "cryocare"...
#################################################
==> Importing the even tomograms:
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestCryoCARE" "Runs/000002_ProtImportTomograms/logs/run.db" 2'

==> Importing the odd tomograms:
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestCryoCARE" "Runs/000073_ProtImportTomograms/logs/run.db" 73'

==> Preparing the training data:
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestCryoCARE" "Runs/000144_ProtCryoCAREPrepareTrainingData/logs/run.db" 144'


*************** last 50 lines of STD OUT *********************

Logging configured. STDOUT --> Runs/000144_ProtCryoCAREPrepareTrainingData/logs/run.stdout , STDERR --> Runs/000144_ProtCryoCAREPrepareTrainingData/logs/run.stderr
RUNNING PROTOCOL -----------------
Protocol starts
Hostname: PC4-0002-D
PID: 251046
pyworkflow: 3.0.27
plugin: cryocare
plugin v: 3.0.1
currentDir: /media/SharedDisk/ScipionProjects/projects/TestCryoCARE
workingDir: Runs/000144_ProtCryoCAREPrepareTrainingData
runMode: Continue
          MPI: 1
      threads: 1
 Starting at step: 1
 Running steps 
STARTED: prepareTrainingDataStep, step 1, time 2022-11-20 17:49:22.421496
FINISHED: prepareTrainingDataStep, step 1, time 2022-11-20 17:49:22.441342
STARTED: runDataExtraction, step 2, time 2022-11-20 17:49:22.479899
 eval "$(/shared/miniconda3/bin/conda shell.bash hook)"&& conda activate cryoCARE-0.1.1 && python $(which cryoCARE_extract_train_data.py) --conf Runs/000144_ProtCryoCAREPrepareTrainingData/extra/training_data_config/training_data_config
FAILED: runDataExtraction, step 2, time 2022-11-20 17:49:24.084480
*** Last status is failed 
------------------- PROTOCOL FAILED (DONE 2/3)

*************** end of STD OUT *********************


*************** last 50 lines of STD ERR *********************

2022-11-20 17:49:23.256123: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/bin/cryoCARE_extract_train_data.py", line 33, in <module>
    main()
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/bin/cryoCARE_extract_train_data.py", line 25, in main
    dm.setup(config['odd'], config['even'], n_samples_per_tomo=config['num_slices'],
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/lib/python3.8/site-packages/cryocare/internals/CryoCAREDataModule.py", line 171, in setup
    tes, ves = self.__compute_extraction_shapes__(e, o, tilt_axis_index=['Z', 'Y', 'X'].index(tilt_axis),
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/lib/python3.8/site-packages/cryocare/internals/CryoCAREDataModule.py", line 210, in __compute_extraction_shapes__
    assert even.data.shape[0] > 2 * sample_shape[0]
AssertionError
Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 202, in run
    self._run()
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 253, in _run
    resultFiles = self._runFunc()
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 249, in _runFunc
    return self._func(*self._args)
  File "/shared/scipion3/plugins/scipion-em-cryocare/cryocare/protocols/protocol_prepare_training_data.py", line 123, in runDataExtraction
    Plugin.runCryocare(self, PYTHON, '$(which cryoCARE_extract_train_data.py) --conf %s' % self._configFile)
  File "/shared/scipion3/plugins/scipion-em-cryocare/cryocare/__init__.py", line 123, in runCryocare
    protocol.runJob(fullProgram, args, env=cls.getEnviron(gpuId=gpuId), cwd=cwd, numberOfMpi=1)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1480, in runJob
    self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 65, in runJob
    process.runJob(log, programName, params,
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 55, in runJob
    return runCommand(command, env, cwd)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 70, in runCommand
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' eval "$(/shared/miniconda3/bin/conda shell.bash hook)"&& conda activate cryoCARE-0.1.1 && python $(which cryoCARE_extract_train_data.py) --conf Runs/000144_ProtCryoCAREPrepareTrainingData/extra/training_data_config/training_data_config' returned non-zero exit status 1.
Protocol failed: Command ' eval "$(/shared/miniconda3/bin/conda shell.bash hook)"&& conda activate cryoCARE-0.1.1 && python $(which cryoCARE_extract_train_data.py) --conf Runs/000144_ProtCryoCAREPrepareTrainingData/extra/training_data_config/training_data_config' returned non-zero exit status 1.

*************** end of STD ERR *********************

[   FAILED ] TestCryoCARE.testWorkflow


Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/shared/scipion3/plugins/scipion-em-cryocare/cryocare/tests/test_cryoCARE_workflow.py", line 115, in testWorkflow
    prepTrainingDataProt = self._runPrepareTrainingData(importTomoProtEven, importTomoProtOdd)
  File "/shared/scipion3/plugins/scipion-em-cryocare/cryocare/tests/test_cryoCARE_workflow.py", line 37, in _runPrepareTrainingData
    self.launchProtocol(protPrepTrainingData)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/tests/tests.py", line 116, in launchProtocol
    raise Exception("Protocol %s execution failed. See last log lines above for more details." % prot.getRunName())
Exception: Protocol cryocare - CryoCARE Training Data Extraction execution failed. See last log lines above for more details.


[==========] run 1 tests (26.027 secs)

[  FAILED  ] 1 tests

[  PASSED  ] 0 tests

```

**Comment by JorMaister** [comment]
Hi, @MohamadHarastani,
My apologies for the late response. It won't happen again. We updated the plugin to the source version 0.2.0, can you update it in your machine and try again?

**Comment by MohamadHarastani** [comment]
Hi @JorMaister 
No worries, we are all busy with different things. I will give it a try today and let you know how it goes.
Cheers

**Comment by MohamadHarastani** [comment]
I got the same error during installation. 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-gpu 2.3.3 requires numpy<1.19.0,>=1.16.0, but you have numpy 1.24.0 which is incompatible.

```
And during testing, I got an error:
```
*************** last 50 lines of STD ERR *********************

  File "/shared/miniconda3/envs/cryoCARE-0.1.1/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 45, in <module>
    from tensorflow.python import data
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/lib/python3.8/site-packages/tensorflow/python/data/__init__.py", line 25, in <module>
    from tensorflow.python.data import experimental
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/lib/python3.8/site-packages/tensorflow/python/data/experimental/__init__.py", line 96, in <module>
    from tensorflow.python.data.experimental import service
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/lib/python3.8/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 21, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/lib/python3.8/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 25, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/lib/python3.8/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 20, in <module>
    from tensorflow.python.data.util import structure
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py", line 26, in <module>
    from tensorflow.python.data.util import nest
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 41, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/lib/python3.8/site-packages/tensorflow/python/framework/sparse_tensor.py", line 29, in <module>
    from tensorflow.python.framework import constant_op
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 29, in <module>
    from tensorflow.python.eager import execute
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 27, in <module>
    from tensorflow.python.framework import dtypes
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py", line 513, in <module>
    np.object,
  File "/shared/miniconda3/envs/cryoCARE-0.1.1/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'object'
Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 202, in run
    self._run()
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 253, in _run
    resultFiles = self._runFunc()
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 249, in _runFunc
    return self._func(*self._args)
  File "/shared/scipion3/plugins/scipion-em-cryocare/cryocare/protocols/protocol_prepare_training_data.py", line 123, in runDataExtraction
    Plugin.runCryocare(self, PYTHON, '$(which cryoCARE_extract_train_data.py) --conf %s' % self._configFile)
  File "/shared/scipion3/plugins/scipion-em-cryocare/cryocare/__init__.py", line 123, in runCryocare
    protocol.runJob(fullProgram, args, env=cls.getEnviron(gpuId=gpuId), cwd=cwd, numberOfMpi=1)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1480, in runJob
    self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 65, in runJob
    process.runJob(log, programName, params,
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 55, in runJob
    return runCommand(command, env, cwd)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 70, in runCommand
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' eval "$(/shared/miniconda3/bin/conda shell.bash hook)"&& conda activate cryoCARE-0.1.1 && python $(which cryoCARE_extract_train_data.py) --conf Runs/000144_ProtCryoCAREPrepareTrainingData/extra/training_data_config/training_data_config' returned non-zero exit status 1.
Protocol failed: Command ' eval "$(/shared/miniconda3/bin/conda shell.bash hook)"&& conda activate cryoCARE-0.1.1 && python $(which cryoCARE_extract_train_data.py) --conf Runs/000144_ProtCryoCAREPrepareTrainingData/extra/training_data_config/training_data_config' returned non-zero exit status 1.

*************** end of STD ERR *********************

[   FAILED ] TestCryoCARE.testWorkflow


Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/shared/scipion3/plugins/scipion-em-cryocare/cryocare/tests/test_cryoCARE_workflow.py", line 115, in testWorkflow
    prepTrainingDataProt = self._runPrepareTrainingData(importTomoProtEven, importTomoProtOdd)
  File "/shared/scipion3/plugins/scipion-em-cryocare/cryocare/tests/test_cryoCARE_workflow.py", line 37, in _runPrepareTrainingData
    self.launchProtocol(protPrepTrainingData)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/tests/tests.py", line 116, in launchProtocol
    raise Exception("Protocol %s execution failed. See last log lines above for more details." % prot.getRunName())
Exception: Protocol cryocare - CryoCARE Training Data Extraction execution failed. See last log lines above for more details.
```

**Comment by JorMaister** [comment]
What I see is that the environment it's working with is the old one: /shared/miniconda3/envs/cryoCARE-0.1.1/, while, it should be cryoCARE-0.2.0. Thus, I think the problem could be related to a config variable pointing to the old environment. You can check it by executing scipion3 printenv.

In my case, I have this --> export CRYOCARE_ENV_ACTIVATION="conda activate cryoCARE-0.2.0"

If you are using a config file with scipion, maybe the problem is there. On the other hand, could you please check if the environment cryoCARE-0.2.0 was created in your machine? To do that, execute conda env list

**Comment by MohamadHarastani** [comment]
The PR that is draft should probably be merged.. I am testing that branch now

**Comment by MohamadHarastani** [comment]
Everything looks fine on this branch
The only thing that feels strange to me is loading a model
It requires a directory that contains the training data.. maybe it can point to a protocol that has prepared training data instead
Otherwise, all good. I will test using it :-)

**Comment by JorMaister** [comment]
My fault. I was expecting something that had to be checked from the cryoCARE side and that's the reason why that PR is in a draft state. It seems that they released the v0.2.1 with some fixes solved. Hence, I'll update the installer with it and let you know when it's ready. Many thanks, @MohamadHarastani

**Comment by MohamadHarastani** [comment]
Thanks a lot @JorMaister
I tested it on a tomogram and I like it very much. Thanks for bringing it to Scipion.
Cheers
Mohamad

**Comment by JorMaister** [comment]
Hi, @MohamadHarastani, 

If you do a gill pull on my branch and re-install the plugin, you'll be installing the v0.2.1 of the source code. I've already pushed it. Remember to update the variable CRYOCARE_ENV_ACTIVATION if you are using a config file.

And thanks to you for testing and collaborating!

**Comment by MohamadHarastani** [comment]
Hi @JorMaister 
Thanks a lot for the updates. I have just updated and everything looks cool.
It seems that you kept the default parameters everywhere except one place, the depth of Unet is set to zero by default in the plygin, I would change that to 3.
It would be nice in the future to have a plotter that shows the loss curve. Just in case one would like to compare the loss obtained between different parameters, or to know how many epochs were actually useful.
Cheers
Mohamad
