### ISSUE TITLE
Protocol failed: Command () returned non-zero exit status 1.

### ISSUE THREAD

**Issue by cryofm** [scipion-em/scipion-em-cryocare#18]
Hello,
I am getting the following error after installing cryocare, it also happens with test data.

> AttributeError: module 'numpy' has no attribute 'typeDict'
> Traceback (most recent call last):
>   File "/home/upiv/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 201, in run
>     self._run()
>   File "/home/upiv/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 252, in _run
>     resultFiles = self._runFunc()
>   File "/home/upiv/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 248, in _runFunc
>     return self._func(*self._args)
>   File "/home/upiv/scipion/Plugins/scipion-em-cryocare/cryocare/protocols/protocol_prepare_training_data.py", line 128, in runDataExtraction
>     Plugin.runCryocare(self, PYTHON, '$(which cryoCARE_extract_train_data.py) --conf %s' % self._configFile)
>   File "/home/upiv/scipion/Plugins/scipion-em-cryocare/cryocare/__init__.py", line 116, in runCryocare
>     protocol.runJob(fullProgram, args, env=cls.getEnviron(gpuId=gpuId), cwd=cwd, numberOfMpi=1)
>   File "/home/upiv/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1487, in runJob
>     self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
>   File "/home/upiv/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 65, in runJob
>     process.runJob(log, programName, params,
>   File "/home/upiv/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 55, in runJob
>     return runCommand(command, env, cwd)
>   File "/home/upiv/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 70, in runCommand
>     check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
>   File "/home/upiv/anaconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
>     raise CalledProcessError(retcode, cmd)
> **subprocess.CalledProcessError: Command ' eval "$(/home/upiv/anaconda3/bin/conda shell.bash hook)"&& conda activate cryoCARE-0.2.1 && python $(which cryoCARE_extract_train_data.py) --conf Runs/000144_ProtCryoCAREPrepareTrainingData/extra/training_data_config/training_data_config' returned non-zero exit status 1.**
>

I also noticed that during installation, tensorflow-gpu 2.4 is installed in the conda environment, which is incompatible with numpy 1.24.
Manually downgrading numpy to 1.19 makes it incompatible with scipy and matplotlib.
Upgrading tensorflow-gpu to 2.11 manually also gives the same error whe testing the protocol.

**Comment by JorMaister** [comment]
Hi, @cryofm,

I remember that as a problem from a previous version. I've noticed that the plugin latest version (3.1.0, with that solved and the tests passing) hasn't been published yet in Pypi. If you're installing the plugins in devel mode, simply do a git pull and reinstall the plugin. If not, We will publish it this morning and let you know when it's available in Pypi.

Sorry for the inconvenience

**Comment by fonsecareyna82** [comment]
The new plugin version fix this error.
